#!/bin/bash

# Security
alias chown="chown --preserve-root"
alias chmod="chmod --preserve-root"
alias chgrp="chgrp --preserve-root"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

if_exist() {
    which $1 > /dev/null 2>/dev/null
    if [ $? -eq 0 ]; then
        eval $2
    else
        [ $# -eq 3 ] && eval $3
    fi
}

# Win time
alias hl='highlight'
alias py='python3'
alias mkdir='mkdir -p'
alias svi="sudo vi"
alias ipt="sudo /sbin/iptables"
alias ipr="ip route show"
alias ipa="ip --brief addr show"
alias ipl="ip link show"
alias ipg="ip route get"
alias dns="dig +short"
alias i="ipython3"
alias e="emacs"
alias ux="chmod u+x"
alias rel="source ~/.zshrc"
alias m="man"
alias aiz="apt-cache search . | fzf | cut -d' ' -f1 | xargs sudo apt-get install"
alias lo="libreoffice"
alias ts="tail -f /var/log/syslog"
alias tf="tail -f"
alias g="git"
alias tref='trans :en :fr'
alias trfe='trans :fr :en'
alias gdb='gdb -q'
alias ush='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias greip="grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'"
alias ssns="ps -o pid,netns -ax|grep '^[0-9 ]\+$'|sort -k2|uniq -f1|awk '{print $1}'|while read a; do nsenter -n -t $a ss -lptn; done"
alias ag="ag --path-to-ignore ~/.ignore_ag"
if_exist batcat "alias bat=batcat"
if_exist bat "alias c='bat --plain --theme TwoDark'" "alias c=cat"
if_exist hexyl "alias x=hexyl" "alias x=xxd"

## Change folder
alias ..='cd ../..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'

# Improve output

## dmesg with readable time
alias dmesg='dmesg -T'

alias less='less -R'
alias diff="colordiff"
alias mountc="mount|column -t"
alias diffw="git diff --word-diff --no-index"
alias difft="diff --brief -r"
alias ip='ip --color'
alias ipb='ip --color --brief'
alias tmux='tmux -2'

kernel=$(uname)
if [ $kernel = "Darwin" ]; then
	SYSTEM_TYPE="OSX"
else
	SYSTEM_TYPE="Linux"
fi
# enable ls colors
  if [[ "$DISABLE_LS_COLORS" != "true" ]]; then
    if [[ "$SYSTEM_TYPE" == "NET_BSD" ]]; then
      # On NetBSD, test if "gls" (GNU ls) is installed (this one supports colors);
      # otherwise, leave ls as is, because NetBSD's ls doesn't support -G
      gls --color -d . &>/dev/null 2>&1 && COLORFLAG="--color=tty"
    elif [[ "$SYSTEM_TYPE" == "OPEN_BSD" ]]; then
      # On OpenBSD, test if "colorls" is installed (this one supports colors);
      # otherwise, leave ls as is, because OpenBSD's ls doesn't support -G
      colorls -G -d . &>/dev/null 2>&1 && COLORFLAG="-G"
    elif [[ "$SYSTEM_TYPE" == "OSX" ]]; then
      # on OS X use "-G"
      COLORFLAG="-G"
	  FOLDER_FIRST=""
    elif ls --color -d . &>/dev/null 2>&1; then
      COLORFLAG="--color"
	  FOLDER_FIRST="--group-directories-first"
      if [[ "$SYSTEM_TYPE" == "LINUX" || "$SYSTEM_TYPE" == "CYGWIN" ]]; then
        COLORFLAG="--color=auto"
      fi
    fi
  fi

## GRC
if which grc >/dev/null 2>&1; then
	alias colour="grc -es --colour=auto"
	alias as="colour as"
	alias configure="colour ./configure"
	alias diff="colour diff"
	alias dig="colour dig"
	alias g++="colour g++"
	alias gas="colour gas"
	alias gcc="colour gcc"
	alias head="colour head"
	alias ifconfig="colour ifconfig"
	alias ld="colour ld"
	alias lsc="colour ls"
	alias make="colour make"
	alias mount="colour mount"
	alias netstat="colour netstat"
	alias ping="colour ping"
	alias ps="colour ps"
	alias tail="colour tail"
	alias traceroute="colour traceroute"
	alias syslog="sudo colour tail -f -n 100 /var/log/syslog"
fi

alias grep="grep $COLORFLAG"
alias egrep="egrep $COLORFLAG"
alias fgrep="fgrep $COLORFLAG"

## ls
alias ls="ls $COLORFLAG"
if_exist lsd "alias lsc=lsd" "alias lsc=ls $COLORFLAG"
if_exist lsd "alias l='lsc -l'" "alias l='lsc -lhF'"

### Show hidden files
alias l.="lsc -dlhF .*"
### displays all files and directories in detail
alias la="lsc -laFh"
### displays all files and directories in detail with newest-files at the bottom
alias lt="lsc -lFhtr"
if_exist lsd "alias ltr='lsd --tree'" "alias ltr=tree"
### sort by file-size
alias lS="lsc -1FShrl"

# System utilities
## get top process eating memory
alias psmem="ps -o time,ppid,pid,nice,pcpu,pmem,user,comm -A | sort -n -k 6"
alias psmem5="psmem | tail -5"
alias psmem10="psmem | tail -10"

## get top process eating cpu
alias grep='grep --color=always'
alias pscpu="ps -o time,ppid,pid,nice,pcpu,pmem,user,comm -A | sort -n -k 5"
alias pscpu5="pscpu | tail -5"
alias pscpu10="pscpu | tail -10"

## shows the corresponding process to ...
alias psx="ps auxwf | grep "

## show the biggest files in a folder first
alias du_overview='du -h | grep "^[0-9,]*[MG]" | sort -hr'

# List of package
alias get_packages='grep -v -E "^rc" | cut -d" " -f3 | paste -sd" "'
